#!/bin/sh
#
# capture - POSIX compliant stdout/stderr/exit code capture

DLM=$(printf '\032')
LF='
'

capture() {
    if [ "$KSH_VERSION" = "Version AJM 93u+ 2012-08-01" ]; then
        stdout=$( (printf "${DLM}%s${DLM}" "$(trap 'printf "${DLM}%d" "$?"' EXIT; "$@" 3>&1 1>&2 2>&3)" ) 2>&1 )
        exitcode=${stdout%"${DLM}"*"${DLM}"}
        exitcode=${exitcode#*"${DLM}"}
        stderr=${stdout%"${DLM}"}
        stderr=${stderr##*"${DLM}"}
        stderr=${stderr%"${LF}"}
        stdout=${stdout%%"${DLM}"*}
        stdout=${stdout%"${LF}"}
    else
        stdout=$( (printf "${DLM}%s${DLM}" "$(trap 'printf "${DLM}%d" "$?"' EXIT; "$@")" 1>&2) 2>&1 )
        exitcode=${stdout%"${DLM}"}
        exitcode=${exitcode##*"${DLM}"}
        stderr=${stdout%%"${DLM}"*}
        stderr=${stderr%"${LF}"}
        stdout=${stdout#*"${DLM}"}
        stdout=${stdout%"${DLM}"*"${DLM}"}
        stdout=${stdout%"${LF}"}
    fi

    return "$exitcode"
}

capture "$@"

[ -n "$stderr" ] && printf >&2 '%s\n' "$stderr"
[ -n "$stdout" ] && printf     '%s\n' "$stdout"

exit "$exitcode"
