#!/bin/sh
#
# capture - POSIX compliant stdout/stderr/exit code capture

DLM="$(printf '\032')"
LF='
'

capture() {
    stdout="$( (printf "${DLM}%s${DLM}" "$(trap 'printf "${DLM}%d" "$?"' EXIT; "$@")" 1>&2) 2>&1 )"
    exitcode="${stdout%"${DLM}"}"
    exitcode="${exitcode##*"${DLM}"}"
    stderr="${stdout%%"${DLM}"*}"
    stderr="${stderr%"${LF}"}"
    stdout="${stdout#*"${DLM}"}"
    stdout="${stdout%"${DLM}"*"${DLM}"}"
    stdout="${stdout%"${LF}"}"

    return "$exitcode"
}

capture "$@"

[ -n "$stderr" ] && printf '%s\n' "$stderr"
[ -n "$stdout" ] && printf '%s\n' "$stdout"

exit "$exitcode"
